env:
  global:
  - secure: e2nalOiGPTg2z5QvOvfzToH22TSj2tqMZF8AvVZE2Qyerd0Kyxxyg0kHahLuU7Hd01iJad1Wb9ToHrlGEWSGttTk7Qp4VqW+7mmrm59KD7G0jQsND5gZ2NJBlLtKhor8b54W7zyA1cTnmJ0IxWqWbxXNGPW7w/UFfjjtAbDrawY=
  - secure: ocWUAMzHGckT8JHRBQEKyvOf+T2y9tQRcfUn2JdX+JXHCCwf3lWFw+1CoqNqFBcnWIEffAqm0+WvhBLjD1O353SlwIhBYsA8wLp3PiJhBsJBUSEUMXeg1KQMUaFQzn9b/95HkSAUEKArLii1uethTrmagPszt18vnouF7n/xK7M=
  - secure: iGE8JmELYHmIPbR6aAZU0oFVHK4gPR7eqBUzsE3E6hxVOBE+h50rieh8Fn5vA/5XgCepWr6oR8dx+4RGA0k4aXHxa4ShBe6kh1Orss3asPl/ZvsnHJYDJVgEgaUNTl5HNyBi2RtTdow1D6yrwaULIdiC3uaARzKr4r+ZadWR2LU=
  - secure: fTg3iBEwdTjjQAePf9Wf7+k9RUzOEzVY1Akl+xJeAAS7PO+8JM4bLDcxPK4ox2A/xLZpk/zHzftpW5WiVMawgRUg/rZBekebukO4xSctHBGApMIXKKNlinyok3oKCiiMTuLza3RzWw4pS6e5yIhi/xMhCkyfT4/KD6pDNWMpgjo=
language: cpp
compiler:
- gcc
# -clang
before_install:
- git submodule update --init --recursive
before_script:
- sudo add-apt-repository ppa:ukplc-team/testing -y
- sudo apt-get update -qq
- sudo apt-get install wput libboost1.49-dev libboost-chrono1.49-dev libboost-date-time1.49-dev
  libboost-filesystem1.49-dev libboost-iostreams1.49-dev libboost-locale1.49-dev libboost-program-options1.49-dev
  libboost-regex1.49-dev libboost-serialization1.49-dev libboost-signals1.49-dev libboost-system1.49-dev
  libboost-test1.49-dev libboost-thread1.49-dev libboost-timer1.49-dev -y -q
- ls -l /usr/lib/libboost*
- pushd src/external/ctemplate
- ./configure --prefix $TRAVIS_BUILD_DIR/src/external/ctemplate
- make
- make install
- popd
- find /usr/lib -name 'libicu*'
- mkdir -p $TRAVIS_BUILD_DIR/src/external/libicu48/lib
- cp /usr/lib/libicu*.so.48 $TRAVIS_BUILD_DIR/src/external/libicu48/lib || true
- ls -l $TRAVIS_BUILD_DIR/src/external/libicu48/lib
- mkdir travis-build
- cd travis-build
- cmake --version
- cmake -D CMAKE_BUILD_TYPE=Distribution -D CMAKE_VERBOSE_MAKEFILE=FALSE ../src
script: make && pushd test && ./teststorage && popd
after_success:
- make package berg_extract
- ls -l Berg*.zip
- cd
- wput README.md ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST/upload/ --reupload
- pushd travis-build/exp && wput echo exptemplate hello_world show_rpath simple_regex ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST/upload/ --reupload --less-verbose; popd
