language: cpp
compiler:
  - gcc
#  - clang
before_install:
  - git submodule update --init --recursive
before_script:
  - pushd src/external/ctemplate
  - ./configure
  - make
  - popd
  - sudo apt-get install libboost-all-dev
  - make install
  - mkdir build
  - cd build
  - cmake ../src
script: make
