language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init --recursive
before_script:
  ### use the PPA ppa:ukplc-team/testing to get Boost 1.49 in Precise
  - sudo add-apt-repository ppa:ukplc-team/testing -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.49-dev libboost-chrono1.49-dev libboost-date-time1.49-dev libboost-filesystem1.49-dev libboost-iostreams1.49-dev libboost-locale1.49-dev libboost-program-options1.49-dev libboost-regex1.49-dev libboost-serialization1.49-dev libboost-signals1.49-dev libboost-system1.49-dev libboost-test1.49-dev libboost-thread1.49-dev libboost-timer1.49-dev -y -q
  - ls -l /usr/lib/libboost*
  ### Build ctemplate:
  - pushd src/external/ctemplate
  - ./configure --prefix $TRAVIS_BUILD_DIR/src/external/ctemplate
  - make
  - make install
  - popd
  ### copy libicu
  - find /usr/lib -name 'libicu*'
  - mkdir -p $TRAVIS_BUILD_DIR/src/external/libicu48/lib
  - cp /usr/lib/libicu*.so.48 $TRAVIS_BUILD_DIR/src/external/libicu48/lib || true
  # - cp /usr/lib/x86_64-linux-gnu/libicu*.so.48 $TRAVIS_BUILD_DIR/src/external/libicu48/lib - Verzeichnis in der VM nicht vorhanden
  - ls -l $TRAVIS_BUILD_DIR/src/external/libicu48/lib
  ### Generate Makefile using CMake
  - mkdir travis-build
  - cd travis-build
  - cmake --version
  #- cmake -D CMAKE_VERBOSE_MAKEFILE=true -D CMAKE_BUILD_TYPE=Distribution ../src
  - cmake -D CMAKE_BUILD_TYPE=Distribution ../src
script: make && pushd test && ./teststorage && popd
