language: cpp
compiler:
  - gcc
#  - clang
before_install:
  - git submodule update --init --recursive
before_script:
  - pushd src/external/ctemplate
  - ./configure --prefix $TRAVIS_BUILD_DIR/src/external/ctemplate
  - make
  - make install
  - popd
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev
  - ls -l /usr/lib/libboost*
  - find /usr/lib -name 'libicu*'
  - mkdir -p $TRAVIS_BUILD_DIR/src/external/libicu48/lib
  - cp /usr/lib/x86_64-linux-gnu/libicu*.so.48 $TRAVIS_BUILD_DIR/src/external/libicu48/lib
  - ls -l $TRAVIS_BUILD_DIR/src/external/libicu48/lib
  - mkdir travis-build
  - cd travis-build
  - cmake --version
  - cmake ../src
script: make && pushd test && ./teststorage && popd
