language: cpp
compiler:
  - gcc
#  - clang
before_install:
  - git submodule update --init --recursive
before_script:
  - pushd src/external/ctemplate
  - ./configure --prefix $TRAVIS_BUILD_DIR/src/external/ctemplate
  - make
  - make install
  - popd
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev
  - ls -l /usr/lib/libboost*
  - mkdir travis-build
  - cd travis-build
  - cmake ../src
script: make
