env:
  global:
  - secure: k7XQ1+F5z/i49XgqePdjHB32PyjF7LxUn2dtFBG1W3cwpUm8WQQSvt4q7gLAH73Sh0v4NXpL1R6M04EZfbrpU9y00QpIkjzWzunjjeYZtDBRzbaSDqnR8CMXKS9J/aG0aTDzMFfvRwHjH4PC/YWzLoguulSJP/ehr0VbLJiLSzM=
  - secure: gpudPjJYyxFNxeBC3yKxUQ//eVlgOib3+TC/H9WpplvAXmune7Hyobpp6V5zV9cyypmhZvO1lftgqS6NO2DbHlXnljHrD1kOWLFRe0/bazi6rxhvVkjyZOAkrP9mtqKA1riydeNgeEqcmoqPzi6GZ1zahi68Amj8UTosoRoWjjA=
  - secure: PtmjgbGjaB3Ta5fIxwuA1bfK2Q0TgAP2ZvoMuVak/2CRHaArnwQodS3JacpPPHEjpqINe65IUvLpgXCONC0OBl3o/fJb0n7LzBnENqXYyU6wsHWb8aI2d7pOaWSm7C4pvZjiXcCbLUPKD3Cc90N8iR+eAABKdUm4GfiaT99ubS0=
language: cpp
compiler:
- gcc
- clang
before_install:
- perl -v
- lsb_release -a
- date +%H:%M:%S.%N
- git submodule update --init --recursive
before_script:
- date +%H:%M:%S.%N
- sudo add-apt-repository ppa:ukplc-team/testing -y
- sudo apt-get update -qq
# Install Apache etc.
- sudo apt-get install wget apache2 apache2-suexec-custom apache2-utils -y
# wput is used to copy the package to an FTP site.
- sudo apt-get install wput -y
# boost 1.49 is used be the C++ part
- sudo apt-get install libboost1.49-dev libboost-chrono1.49-dev libboost-date-time1.49-dev libboost-filesystem1.49-dev libboost-iostreams1.49-dev libboost-locale1.49-dev libboost-program-options1.49-dev libboost-regex1.49-dev libboost-serialization1.49-dev libboost-signals1.49-dev libboost-system1.49-dev libboost-test1.49-dev libboost-thread1.49-dev -y -qq
- ls -l /usr/lib/libboost*
- date +%H:%M:%S.%N
- pushd src/external/ctemplate
- ./configure --prefix $TRAVIS_BUILD_DIR/src/external/ctemplate
- make
- make install
- popd
- date +%H:%M:%S.%N
- find /usr/lib -name 'libicu*'
- mkdir -p $TRAVIS_BUILD_DIR/src/external/libicu48/lib
- cp /usr/lib/libicu*.so.48 $TRAVIS_BUILD_DIR/src/external/libicu48/lib || true
- ls -l $TRAVIS_BUILD_DIR/src/external/libicu48/lib
- mkdir travis-build
- cd travis-build
- date +%H:%M:%S.%N
- cmake --version
- cmake -D CMAKE_BUILD_TYPE=Distribution -D CMAKE_VERBOSE_MAKEFILE=FALSE ../src
#- cmake -D CMAKE_BUILD_TYPE=Distribution -D CMAKE_VERBOSE_MAKEFILE=TRUE ../src
- date +%H:%M:%S.%N
script: make && pushd test && ./bergunittests && popd && $TRAVIS_BUILD_DIR/www/cgi-bin/brg/t/run_tests.sh
after_success:
- date +%H:%M:%S.%N
#- make package berg_extract
- make package
- ls -l Berg*.zip
- date +%H:%M:%S.%N
- wput Berg*.zip ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST/upload/ --reupload --less-verbose
#- cd ..
#- wput README.md ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST/upload/ --reupload
#- pushd travis-build/exp && wput echo exptemplate hello_world show_rpath simple_regex ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST/upload/ --reupload --less-verbose; popd
- date +%H:%M:%S.%N
# Test Default Apache installation:
- wget http://127.0.0.1/index.html
- cat index.html


